In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Best model

# SVC = 'C'= 1000, 'gamma' = 0.01, 'kernel' ='rbf'

In [2]:

import pandas as pd
import numpy as np

In [3]:
import torch

In [4]:
CHINESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/CHINESE_merged.csv"
FRENCH_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/FRENCH_merged.csv"
GERMAN_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/GERMAN_merged.csv"
JAPANESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/JAPANESE_merged.csv"
PORTUGUESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/PORTUGUESE_merged.csv"
ROMANIAN_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/ROMANIAN_merged.csv"
ALL_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/ALL_merged.csv"
# VALID_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/valid_new.csv"
TEST_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/test.csv"
# TRAIN_DATASET_PATH = "train_new.csv"
# VALID_DATASET_PATH = "valid_new.csv"
# TEST_DATASET_PATH = "test.csv"

In [5]:
# CHINESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/CHINESE_merged.csv"
# FRENCH_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/FRENCH_merged.csv"
# GERMAN_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/GERMAN_merged.csv"
# JAPANESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/JAPANESE_merged.csv"
# PORTUGUESE_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/PORTUGUESE_merged.csv"
# ROMANIAN_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/ROMANIAN_merged.csv"
# ALL_TRAIN_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/BackTranslation/ALL_merged.csv"
# # VALID_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/valid_new.csv"
# TEST_DATASET_PATH = "/content/drive/MyDrive/FYP/Davidson_Sampling/test.csv"
# # TRAIN_DATASET_PATH = "train_new.csv"
# # VALID_DATASET_PATH = "valid_new.csv"
# # TEST_DATASET_PATH = "test.csv"

In [6]:
# train_dataset= pd.read_csv(TRAIN_DATASET_PATH)

In [7]:
# train_dataset

In [8]:
# from sklearn.model_selection import train_test_split

In [9]:
# X_train, X_valid, y_train, y_valid = train_test_split(train_dataset['tweet'], train_dataset["label"], test_size=0.3, random_state=42)

In [10]:
# X_valid

In [11]:
# y_valid

In [12]:
# features_df = pd.DataFrame(X_valid)
# labels_df = pd.DataFrame(y_valid)

# # Concatenate features and labels along columns axis
# combined_df = pd.concat([features_df, labels_df], axis=1)

In [13]:
# combined_df

In [14]:
# combined_df.to_csv('/content/drive/MyDrive/FYP/Davidson_Sampling/valid_new.csv', index=False)

In [15]:
test_dataset = pd.read_csv(TEST_DATASET_PATH)

In [16]:
# valid_dataset = pd.read_csv(VALID_DATASET_PATH)

In [17]:

# Load model directly
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("roberta-base")
model = AutoModel.from_pretrained("roberta-base")


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [19]:
model.to(device)
model.eval()

RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): RobertaEncoder(
    (layer): ModuleList(
      (0-11): 12 x RobertaLayer(
        (attention): RobertaAttention(
          (self): RobertaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): RobertaSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropou

In [20]:
# seq_len = [len(tweet.split()) for tweet in train_dataset['tweet']]

In [21]:
# pd.Series(seq_len).hist(bins=40,color='firebrick')

In [22]:
# MAX_LENGTH = 24

In [23]:
from torch.utils.data import DataLoader

In [24]:
# train_dataset['tweet'].count()

#Train

In [25]:
from torch.utils.data import TensorDataset
import pandas as pd

def create_train_tokens(train_dataset_path):
  train_dataset= pd.read_csv(train_dataset_path)
  seq_len = [len(tweet.split()) for tweet in train_dataset['tweet']]
  MAX_LENGTH = np.percentile(seq_len, 90)
  print(MAX_LENGTH)
  train_tokens= tokenizer.batch_encode_plus(train_dataset['tweet'].tolist(),padding='max_length',max_length=int(MAX_LENGTH),truncation=True)
  # tokenized_train_datasets=t.with_format("torch")

# Assuming train_tokens contains the tokenized and encoded inputs
  input_ids = torch.tensor(train_tokens['input_ids'])
  attention_masks = torch.tensor(train_tokens['attention_mask'])

# Create a TensorDataset
  train_new_dataset = TensorDataset(input_ids, attention_masks)

# Use the DataLoader with the TensorDataset
  train_dataloader = DataLoader(train_new_dataset, batch_size=400, shuffle=False)
  all_outputs_train_tensor = torch.tensor([], device=device)
  for batch in train_dataloader:
    input_ids, attention_masks = batch
    input_ids = input_ids.to(device)
    attention_masks = attention_masks.to(device)

    with torch.no_grad():
        outs = model(input_ids, token_type_ids=None, attention_mask=attention_masks)
        bert_cls_hidden_state = outs[1]
        all_outputs_train_tensor = torch.cat([all_outputs_train_tensor, bert_cls_hidden_state], dim=0)
  all_outputs_train_cpu = all_outputs_train_tensor.cpu()
  all_outputs_train_numpy = all_outputs_train_cpu.numpy()
  labels = train_dataset['class']
  features_df = pd.DataFrame(all_outputs_train_numpy)
  labels_df = pd.DataFrame(labels)

  # Concatenate features and labels along columns axis
  combined_df = pd.concat([features_df, labels_df], axis=1)




  x_train_features = combined_df.iloc[:, :-1]
  y_train_lables = combined_df['class']
  return x_train_features,y_train_lables

#Test

In [26]:
seq_len = [len(tweet.split()) for tweet in test_dataset['tweet']]
MAX_LENGTH = np.percentile(seq_len, 90)
print(MAX_LENGTH)

24.0


In [27]:
test_tokens = tokenizer.batch_encode_plus(test_dataset['tweet'].tolist(),padding='max_length',max_length=int(MAX_LENGTH),truncation=True)

In [28]:
# tokenized_train_datasets=t.with_format("torch")
from torch.utils.data import TensorDataset

# Assuming train_tokens contains the tokenized and encoded inputs
input_ids = torch.tensor(test_tokens['input_ids'])
attention_masks = torch.tensor(test_tokens['attention_mask'])

# Create a TensorDataset
test_new_dataset = TensorDataset(input_ids, attention_masks)

# Use the DataLoader with the TensorDataset
test_dataloader = DataLoader(test_new_dataset, batch_size=400, shuffle=False)

In [29]:
all_outputs_test_tensor = torch.tensor([], device=device)

In [30]:
# for batch in test_dataloader:
#         batch = {k: v.to(device) for k, v in batch.items()}
#         with torch.no_grad():
#           outs = model(batch['input_ids'], token_type_ids=None, attention_mask=batch['attention_mask'])
#           b_logit_pred = outs.logits

#           pred_label = torch.sigmoid(b_logit_pred)

#           all_outputs_test_tensor = torch.cat([all_outputs_test_tensor, pred_label], dim=0)
#           print(all_outputs_test_tensor)

In [31]:
for batch in test_dataloader:
    input_ids, attention_masks = batch
    input_ids = input_ids.to(device)
    attention_masks = attention_masks.to(device)

    with torch.no_grad():
        outs = model(input_ids, token_type_ids=None, attention_mask=attention_masks)
        bert_cls_hidden_state = outs[1]
        all_outputs_test_tensor = torch.cat([all_outputs_test_tensor, bert_cls_hidden_state], dim=0)


In [32]:
all_outputs_test_cpu = all_outputs_test_tensor.cpu()

In [33]:
all_outputs_test_numpy = all_outputs_test_cpu.numpy()

In [34]:
import pandas as pd

# Assuming train_dataset['label'] is a numpy array
labels = test_dataset['label']

# Convert numpy arrays to pandas DataFrames
features_test_df = pd.DataFrame(all_outputs_test_numpy)
labels_test_df = pd.DataFrame(labels)

# Concatenate features and labels along columns axis
combined_test_df = pd.concat([features_test_df, labels_test_df], axis=1)




In [35]:
combined_test_df

0         1         2         3         4         5         6  \
0     0.270542 -0.198513 -0.095274 -0.455503  0.193123 -0.198474 -0.508735   
1     0.275510 -0.198115 -0.085319 -0.442803  0.190293 -0.199634 -0.513740   
2     0.280671 -0.198145 -0.097603 -0.437210  0.179467 -0.193282 -0.513613   
3     0.282447 -0.195370 -0.101017 -0.433028  0.182143 -0.199903 -0.505649   
4     0.268755 -0.182967 -0.082876 -0.437180  0.178934 -0.189237 -0.511936   
...        ...       ...       ...       ...       ...       ...       ...   
2474  0.265397 -0.222458 -0.092998 -0.426612  0.173024 -0.202600 -0.529690   
2475  0.300964 -0.217831 -0.132249 -0.428984  0.204666 -0.206501 -0.531209   
2476  0.318831 -0.213037 -0.136846 -0.442423  0.230161 -0.189669 -0.516154   
2477  0.276135 -0.194606 -0.100236 -0.435772  0.188242 -0.194586 -0.512354   
2478  0.266858 -0.210373 -0.105411 -0.423433  0.188537 -0.188592 -0.516323   

             7         8         9  ...       759       760       761  \
0    -0.146952 -0.401737 -0.156574  ... -0.039020 -0.222998 -0.008822   
1    -0.140734 -0.415956 -0.168757  ... -0.045953 -0.207168 -0.010750   
2    -0.142820 -0.407163 -0.172770  ... -0.050106 -0.216113 -0.014336   
3    -0.133593 -0.397729 -0.170679  ... -0.047544 -0.209629 -0.013999   
4    -0.132354 -0.390328 -0.165372  ... -0.074010 -0.205234  0.007062   
...        ...       ...       ...  ...       ...       ...       ...   
2474 -0.152816 -0.399633 -0.171101  ... -0.065771 -0.224775 -0.020036   
2475 -0.142573 -0.416853 -0.167296  ... -0.063734 -0.225541 -0.011366   
2476 -0.186311 -0.443920 -0.158864  ... -0.039559 -0.254972 -0.038283   
2477 -0.158892 -0.399475 -0.183976  ... -0.059983 -0.227160 -0.021352   
2478 -0.129762 -0.402750 -0.192344  ... -0.062342 -0.217584 -0.023730   

           762       763       764       765       766       767  label  
0    -0.080591  0.186590 -0.156736 -0.107359 -0.009997 -0.011794      1  
1    -0.065911  0.185796 -0.143013 -0.101327 -0.019874 -0.028288      1  
2    -0.067625  0.176783 -0.153666 -0.100040 -0.011861 -0.010891      2  
3    -0.068177  0.181721 -0.170023 -0.081797 -0.015382 -0.019258      1  
4    -0.049844  0.181202 -0.154653 -0.096108 -0.000823 -0.007260      1  
...        ...       ...       ...       ...       ...       ...    ...  
2474 -0.088493  0.166610 -0.132768 -0.072652 -0.011950 -0.028654      1  
2475 -0.066957  0.208813 -0.132103 -0.101391 -0.009816 -0.021706      2  
2476 -0.074208  0.199257 -0.144077 -0.135033  0.000494 -0.023511      1  
2477 -0.067753  0.178262 -0.150593 -0.095100 -0.005203 -0.041936      2  
2478 -0.084321  0.178295 -0.158656 -0.088499 -0.019462  0.000795      1  

[2479 rows x 769 columns]

In [36]:
# with torch.no_grad():
#     train_outputs = model(input_ids=train_seq, attention_mask=train_mask)

# # Extract the embeddings from the BERT model
# train_embeddings = train_outputs.last_hidden_state[:, 0, :].numpy()

In [37]:
x_test_features = combined_test_df.iloc[:, :-1]
y_test_lables = combined_test_df['label']

In [38]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


In [39]:
def score(y_test_lables,y_pred):
  accuracy = accuracy_score(y_test_lables, y_pred)
  precision = precision_score(y_test_lables, y_pred,average='macro')
  recall = recall_score(y_test_lables, y_pred,average='macro')
  f1 = f1_score(y_test_lables, y_pred,average='macro')
  conf_matrix = confusion_matrix(y_test_lables, y_pred)
  return accuracy,precision,recall,f1,conf_matrix

In [40]:
# !pip install xgboost
# from xgboost import XGBClassifier
from sklearn.svm import SVC
def model_test(x_train_features,x_test_features,y_train_lables,y_test_lables):


# from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid
# param_grid = {
#     'max_depth': [3, 5, 7],
#     'learning_rate': [0.1, 0.01, 0.001],
#     'subsample': [0.5, 0.7, 1]
# }

# Create the XGBoost model object
#need
  # xgb_model = XGBClassifier()
  model=SVC(C=1000,gamma=0.01,kernel='rbf')

# Create the GridSearchCV object
# grid_search = GridSearchCV(xgb_model, param_grid, cv=5, scoring='accuracy')

# Fit the GridSearchCV object to the training data
  model.fit(x_train_features, y_train_lables)
  y_pred = model.predict(x_test_features)
  accuracy,precision,recall,f1,conf_matrix = score(y_test_lables,y_pred)
  return accuracy,precision,recall,f1,conf_matrix

# Print the best set of hyperparameters and the corresponding score
# print("Best set of hyperparameters: ", grid_search.best_params_)

#CHINESE_merged

In [41]:

x_train_features_CHINESE,y_train_lables_CHINESE = create_train_tokens(CHINESE_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_CHINESE,x_test_features,y_train_lables_CHINESE,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.5788488747808938
0.8410649455425575
0.5559716620788255
0.6504383018883967
[[  16  134   14]
 [  19 1816   70]
 [  13  144  253]]


#ROMANIAN_merged

In [42]:
x_train_features_ROMANIAN,y_train_lables_ROMANIAN = create_train_tokens(ROMANIAN_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_ROMANIAN,x_test_features,y_train_lables_ROMANIAN,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.579195524322126
0.8430818878580073
0.5549890105200265
0.6729409925255326
[[  15  137   12]
 [  15 1822   68]
 [   8  149  253]]


#PORTUGUESE_merged

In [43]:
x_train_features_PORTUGUESE,y_train_lables_PORTUGUESE = create_train_tokens(PORTUGUESE_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_PORTUGUESE,x_test_features,y_train_lables_PORTUGUESE,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.5558601637735093
0.8386446147640177
0.5393668779207478
0.6225049845135113
[[   9  141   14]
 [  14 1821   70]
 [  12  149  249]]


#JAPANESE_merged

In [44]:
x_train_features_JAPANESE,y_train_lables_JAPANESE = create_train_tokens(JAPANESE_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_JAPANESE,x_test_features,y_train_lables_JAPANESE,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.578028889349644
0.8398547801532876
0.5541706676909288
0.6513516349023217
[[  16  136   12]
 [  21 1815   69]
 [  11  148  251]]


#GERMAN_merged

In [45]:
x_train_features_GERMAN,y_train_lables_GERMAN = create_train_tokens(GERMAN_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_GERMAN,x_test_features,y_train_lables_GERMAN,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.5673799545686715
0.8430818878580073
0.5481968717324969
0.6693457773311425
[[  11  140   13]
 [   9 1825   71]
 [   8  148  254]]


#FRENCH_merged

In [46]:
x_train_features_FRENCH,y_train_lables_FRENCH = create_train_tokens(FRENCH_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_FRENCH,x_test_features,y_train_lables_FRENCH,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.5894268015592523
0.8418717224687374
0.5618376971171286
0.6672745203729648
[[  20  132   12]
 [  20 1817   68]
 [  13  147  250]]


#ALL_merged

In [47]:
x_train_features_ALL,y_train_lables_ALL = create_train_tokens(ALL_TRAIN_DATASET_PATH)
accuracy,precision,recall,f1,conf_matrix = model_test(x_train_features_ALL,x_test_features,y_train_lables_ALL,y_test_lables)
print(f1)
print(accuracy)
print(recall)
print(precision)
print(conf_matrix)

24.0
0.6022859629260319
0.8035498184751916
0.6010135928130934
0.6297408017126327
[[  60   95    9]
 [ 140 1711   54]
 [  70  119  221]]


#LogisticRegression

In [48]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import GridSearchCV
# logistic_regression = LogisticRegression()
# param_grid = {
#     'C': [0.001, 0.01, 0.1],
#     'penalty': ['l1', 'l2'],
#     'solver': ['liblinear','saga']
# }

# grid_search = GridSearchCV(estimator=logistic_regression, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)

# grid_search.fit(x_valid_features, y_valid_lables)

# print("Best Parameters:", grid_search.best_params_)

In [49]:
# y_pred = grid_search.predict(x_test_features)


In [50]:
# accuracy,precision,recall,f1,conf_matrix = score (y_test_lables,y_pred)

In [51]:
# print(f1)
# print(accuracy)
# print(recall)
# print(precision)
# print(conf_matrix)

#XGBoost

#KNN

In [52]:
# from sklearn.neighbors import KNeighborsClassifier

# knn = KNeighborsClassifier()

# # Define hyperparameters to tune
# param_grid = {
#     'n_neighbors': [3, 5, 7, 9],
#     'weights': ['uniform', 'distance'],
#     'metric': ['euclidean', 'manhattan']
# }

# grid_search = GridSearchCV(estimator=knn, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)
# grid_search.fit(x_valid_features, y_valid_lables)

# print("Best Parameters:", grid_search.best_params_)


In [53]:
# y_pred = grid_search.predict(x_test_features)

In [54]:
# accuracy,precision,recall,f1,conf_matrix = score (y_test_lables,y_pred)

In [55]:
# print(f1)
# print(accuracy)
# print(recall)
# print(precision)
# print(conf_matrix)

#SVC

In [56]:
# #Hyper Parameter Tuning For SVC
# from sklearn.svm import SVC
# from sklearn.model_selection import GridSearchCV

# # defining parameter range
# # param_grid = {'C': [0.1, 1, 10, 100, 1000],
# #               'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
# #               'kernel': ['rbf']}
# param_grid = {'C': [0.1, 1, 10],
#              'gamma': [1, 0.1, 0.01],
#              'kernel': ['rbf']}

# grid = GridSearchCV(SVC(), param_grid, cv=5, refit = True, verbose = 3)

# # fitting the model for grid search
# grid.fit(x_valid_features, y_valid_lables)
# grid.best_params_


In [57]:
# y_pred = grid.predict(x_test_features)

In [58]:
# accuracy,precision,recall,f1,conf_matrix = score (y_test_lables,y_pred)

In [59]:
# print(f1)
# print(accuracy)
# print(recall)
# print(precision)
# print(conf_matrix)